name: rick_and_morty
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # state management
  provider: ^6.1.1

  # network manager
  dio: ^5.4.0

  # route management
  auto_route: ^7.8.4

  #core
  async: ^2.11.0

  #ui
  dot_navigation_bar: ^1.0.2
  lottie: ^2.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.7


flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/image/
